trigger:
  - main

pr: none

pool:
  vmImage: ubuntu-latest

resources:
  repositories:
  # From the branch called feature/fe-purejs-library-template
    - repository: templates
      type: git
      name: DevOps/azure-pipeline-templates

extends:
  template: pipeline-fe-nobuild-library.yaml@templates
  parameters:
    libraryName: 'cp-openapi-gen-plugin'
